kind: Simple
apiVersion: k3d.io/v1alpha3
name: dev-cluster
servers: 3
agents: 3
kubeAPI:
  hostIP: 0.0.0.0
  hostPort: "6443"
image: rancher/k3s:v1.26.4-k3s1
volumes:
- volume: /tmp:/tmp/k3d
  nodeFilters:
  - all
ports:
- port: 8080:80
  nodeFilters:
  - loadbalancer
- port: 0.0.0.0:8443:443
  nodeFilters:
  - loadbalancer
options:
  k3d:
    wait: true
    timeout: 6m0s
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
  k3s:
    extraArgs:
    - arg: --tls-san=127.0.0.1
      nodeFilters:
      - server:*
    nodeLabels: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime:
    gpuRequest: ""
    serversMemory: ""
    agentsMemory: ""
    labels:
    - label: foo=bar
      nodeFilters:
      - server:0
      - loadbalancer
env:
- envVar: bar=baz
  nodeFilters:
  - all