#!/bin/bash

source ./lib/colors

status_apps_resources="0"

# Apps manifests
color_echo_blue "Deploying apps manifests..."
set -e
for file in bootstrap/apps/*.sh; do
    bash "$file" || status_apps_resources="1"
done
set +e
if [[ "${status_apps_resources}" != 0 ]]; then
    color_echo_red "...Failed to deploy apps manifests."
    exit 1
fi
color_echo_green "...Apps manifests deployed."