#!/bin/bash

source ./lib/colors

status_base_resources="0"

# Base manifests
color_echo_blue "Deploying base manifests..."
set -e
for file in bootstrap/base/*.sh; do
    color_echo_blue "Executing file "${file}"..."
    bash "$file" || status_base_resources="1"

    if [[ "${status_base_resources}" != 0 ]]; then
        color_echo_red "...Failed to deploy base manifests."
        exit 1
    fi

    color_echo_blue "...File "${file}" executed."
done
set +e

color_echo_green "...Base manifests deployed."