#!/bin/bash

source ./lib/colors

status_helm_resources="0"

# Helm apps
color_echo_blue "Deploying helm apps..."
set -e
for file in bootstrap/helm/*.sh; do
    bash "$file" || status_helm_resources="1"
done
set +e
if [[ "${status_helm_resources}" != 0 ]]; then
    color_echo_red "...Failed to deploy helm apps."
    exit 1
fi
color_echo_green "...Helm apps deployed."