#!/bin/bash

INGRESS_HOST=$(kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
INGRESS_DOMAIN=${INGRESS_HOST}.nip.io

for i in $(seq 1 1000); do curl -s -o /dev/null "http://bookinfo.$INGRESS_DOMAIN/productpage" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://bookinfo.$INGRESS_DOMAIN/productpage" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://bookinfo.$INGRESS_DOMAIN/productpage" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://bookinfo.$INGRESS_DOMAIN/productpage" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://bookinfo.$INGRESS_DOMAIN/productpage" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://bookinfo.$INGRESS_DOMAIN/productpage" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://bookinfo.$INGRESS_DOMAIN/productpage" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://bookinfo.$INGRESS_DOMAIN/productpage" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://bookinfo.$INGRESS_DOMAIN/productpage" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://bookinfo.$INGRESS_DOMAIN/productpage" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://nginx-example.$INGRESS_DOMAIN" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://nginx-example.$INGRESS_DOMAIN" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://nginx-example.$INGRESS_DOMAIN" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://nginx-example.$INGRESS_DOMAIN" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://nginx-example.$INGRESS_DOMAIN" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://nginx-example.$INGRESS_DOMAIN" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://nginx-example.$INGRESS_DOMAIN" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://nginx-example.$INGRESS_DOMAIN" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://nginx-example.$INGRESS_DOMAIN" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://nginx-example.$INGRESS_DOMAIN" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://prometheus.$INGRESS_DOMAIN/graph" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://prometheus.$INGRESS_DOMAIN/graph" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://prometheus.$INGRESS_DOMAIN/graph" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://prometheus.$INGRESS_DOMAIN/graph" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://prometheus.$INGRESS_DOMAIN/graph" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://prometheus.$INGRESS_DOMAIN/graph" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://prometheus.$INGRESS_DOMAIN/graph" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://prometheus.$INGRESS_DOMAIN/graph" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://prometheus.$INGRESS_DOMAIN/graph" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://prometheus.$INGRESS_DOMAIN/graph" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://grafana.$INGRESS_DOMAIN/d/G8wLrJIZk/istio-mesh-dashboard?orgId=1&refresh=5s&from=now-30m&to=now" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://grafana.$INGRESS_DOMAIN/d/G8wLrJIZk/istio-mesh-dashboard?orgId=1&refresh=5s&from=now-30m&to=now" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://grafana.$INGRESS_DOMAIN/d/G8wLrJIZk/istio-mesh-dashboard?orgId=1&refresh=5s&from=now-30m&to=now" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://grafana.$INGRESS_DOMAIN/d/G8wLrJIZk/istio-mesh-dashboard?orgId=1&refresh=5s&from=now-30m&to=now" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://grafana.$INGRESS_DOMAIN/d/G8wLrJIZk/istio-mesh-dashboard?orgId=1&refresh=5s&from=now-30m&to=now" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://grafana.$INGRESS_DOMAIN/d/G8wLrJIZk/istio-mesh-dashboard?orgId=1&refresh=5s&from=now-30m&to=now" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://grafana.$INGRESS_DOMAIN/d/G8wLrJIZk/istio-mesh-dashboard?orgId=1&refresh=5s&from=now-30m&to=now" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://grafana.$INGRESS_DOMAIN/d/G8wLrJIZk/istio-mesh-dashboard?orgId=1&refresh=5s&from=now-30m&to=now" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://grafana.$INGRESS_DOMAIN/d/G8wLrJIZk/istio-mesh-dashboard?orgId=1&refresh=5s&from=now-30m&to=now" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://grafana.$INGRESS_DOMAIN/d/G8wLrJIZk/istio-mesh-dashboard?orgId=1&refresh=5s&from=now-30m&to=now" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://tracing.$INGRESS_DOMAIN/jaeger/search" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://tracing.$INGRESS_DOMAIN/jaeger/search" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://tracing.$INGRESS_DOMAIN/jaeger/search" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://tracing.$INGRESS_DOMAIN/jaeger/search" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://tracing.$INGRESS_DOMAIN/jaeger/search" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://tracing.$INGRESS_DOMAIN/jaeger/search" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://tracing.$INGRESS_DOMAIN/jaeger/search" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://tracing.$INGRESS_DOMAIN/jaeger/search" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://tracing.$INGRESS_DOMAIN/jaeger/search" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://tracing.$INGRESS_DOMAIN/jaeger/search" && sleep 1; done & \
for i in $(seq 1 1000); do curl -s -o /dev/null "http://tracing.$INGRESS_DOMAIN/jaeger/search" && sleep 1; done


